name: classification
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab    # notebooks
  - jupyter_contrib_nbextensions # for TOC
  - numpy         # scientific computing
  - pandas        # data structures
  - scikit-learn  # machine learning libs
  - matplotlib    # plotting
  - seaborn       # visualization based on matplotlib
  - tensorflow
  - keras
  - pydot
  - octave_kernel

