name: sklearn
dependencies:
  - python=3.7
  - jupyter       # for notebook
  - numpy         # scientific computing
  - pandas        # data structures
  - scikit-learn  # machine learning libs
  - matplotlib    # plotting
  - seaborn       # visualization based on matplotlib

